### ISSUE TITLE
Add qpack implementation

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-incubator-codec-http3#1]
http3 uses qpack for compression. We need to have an implementation:

https://quicwg.org/base-drafts/draft-ietf-quic-qpack.html

**Comment by chenzhiguo** [comment]
mark

**Comment by normanmaurer** [comment]
@chenzhiguo does this mean you plan to work on this ?

**Comment by chenzhiguo** [comment]
> @chenzhiguo does this mean you plan to work on this ?

Sorry, don't have the ability yet. I'm just concerned about it.

**Comment by hyperxpro** [comment]
Can't we use Quiche QPACK?

**Comment by normanmaurer** [comment]
In theory yes... that said its currently not exposed as API on their side + I would love to limit the amount of JNI.

**Comment by hyperxpro** [comment]
Agree with the JNI point. I can try for QPACK but I need some help.

**Comment by hyperxpro** [comment]
@normanmaurer Is there any way to verify QPACK implementation? I mean, I want to test if it's correct or not,

**Comment by normanmaurer** [comment]
@kachayev is working on an implementation already

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty-incubator-codec-http3/pull/3
