### ISSUE TITLE
Http3FrameToHttpObjectCodec writes invalid header frame

### ISSUE THREAD

**Issue by valerauko** [netty/netty-incubator-codec-http3#134]
If a LastHttpContent.EMPTY_LAST_CONTENT comes last, Http3FrameToHttpObjectCodec writes an empty header frame.

https://github.com/netty/netty-incubator-codec-http3/blob/6d8e7c28ff072af62b9fa2149af332dd62188a85/src/main/java/io/netty/incubator/codec/http3/Http3FrameToHttpObjectCodec.java#L166-L167

Using the example client (Http3ClientExample) the response generated will throw an error,
```
io.netty.incubator.codec.http3.Http3HeadersValidationException: Not all mandatory pseudo-headers included.
```

**Comment by NiteshKant** [comment]
@valerauko I created https://github.com/netty/netty-incubator-codec-http3/issues/136 for the unexpected behavior today that presence of pseudo headers is also mandated for trailers which I think is what you are observing. Avoiding the header frame for trailers is a good optimization but should not be considered as an invalid message.
