### ISSUE TITLE
Experimental WebTransport support

### ISSUE THREAD

**Issue by fuweichin** [netty/netty-incubator-codec-http3#153]
WebTransport is a protocol framework which is built on top of HTTP/3, similar to WebSocket which is built on top of HTTP/1.1.

Currently I cannot find one WebTransport Server written in Java, I hope netty gives it a try.

See:
Experimenting with WebTransport
https://web.dev/webtransport/

WebTransport over HTTP/3 (draft)
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3/

Sample WebTransport Client
https://googlechrome.github.io/samples/webtransport/client.html

**Comment by NiteshKant** [comment]
We do not have any plans to implement WebTransport yet, if you do have bandwidth, I can help review design/code.

**Comment by mondain** [comment]
@NiteshKant I did a PR over here as I really really need this https://github.com/netty/netty/pull/15771
