### ISSUE TITLE
Any way to close the log?

### ISSUE THREAD

**Issue by klb91** [netty/netty-incubator-codec-http3#179]
I want to close the log for both client and server example.  Can I?

**Comment by normanmaurer** [comment]
@klb91 what does this mean ? You want to "log the close" ?

**Comment by klb91** [comment]
I just do not want the code to output logs. Any way to set this?

I am trying to test how long it will take to transmit a specific file by the example codes. I think the log could effect the result. That is why I want the code to print no log.

**Comment by klb91** [comment]
I have found the way.
