### ISSUE TITLE
TLS Encrypted Client Hello (ECH)

### ISSUE THREAD

**Issue by glennosss** [netty/netty-incubator-codec-http3#190]
Netty supports 'Server Name Indication' (SNI), however presently has no support for 'Encrypted Client Hello' (ECH). ECH replaces the older 'Encrypted SNI' (ESNI) standard which only encrypted the SNI header.

Discussed here: https://en.wikipedia.org/wiki/Server_Name_Indication#Encrypted_Client_Hello

Steps involved;
1. Browser fetches 'HTTPS' dns record with 'ech' public key property - for good example, see: https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-svcb-https-08#section-11.3.3
2. Browser uses this public key to encrypt the 'Client Hello' when connecting to the server - more detail discussed here: https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#section-3.2
3. Server determines which key to decrypt this 'Client Hello' with using a 'config_id' (uint8, limiting a server to a max of 256 different certificates it can serve) - for more information see: https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html#section-4.1
4. Netty presently uses '[io.netty.handler.ssl.SniHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SniHandler.java)' to determine which certificate to serve based off the SNI entry. For ECH, this now changes to needing a new EchHandler capable of mapping a 'config_id' to the relevant certificate.

Unknowns - how does the browser determine the appropriate 'config_id' value to put in the ECH payload?

**Comment by normanmaurer** [comment]
If BoringSSL supports it we should also do

**Comment by glennosss** [comment]
BoringSSL includes support for this;
> "ECH is working for openssl, boringssl, nginx, Apache HTTPD, lighttpd HAProxy, Conscrypt, curl, and more. There is work underway in Firefox and Chromium. It has been sketched out for OkHTTP" - https://youtrack.jetbrains.com/issue/KTOR-3306

**Comment by normanmaurer** [comment]
Ok this should work as it is.

**Comment by Eng-Fouad** [comment]
> Ok this should work as it is.

To be able to use BoringSSL's ECH, some configurations must be set, such as the private key. See https://github.com/google/boringssl/blob/main/include/openssl/ssl.h#L4279-L4344

So I think these functions should be exposed by Netty.
