### ISSUE TITLE
Http3.newQuicClientCodecBuilder().build () takes a long time

### ISSUE THREAD

**Issue by zhining-lu** [netty/netty-incubator-codec-http3#195]
The execution time is up to 40 milliseconds :

 ChannelHandler codec = Http3.newQuicClientCodecBuilder()
                    .sslContext(context)
                    .maxIdleTimeout(5000 * 5000, TimeUnit.MILLISECONDS)
                    .initialMaxData(10000000)
                    .initialMaxStreamDataBidirectionalLocal(1000000)
                    .build();

**Comment by normanmaurer** [comment]
I think there is really nothing we can do about this
