### ISSUE TITLE
http3 Cannot access

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty-incubator-codec-http3#196]
![image](https://user-images.githubusercontent.com/10923974/173333823-ef4d5e9b-e94b-4e25-8026-c3728b46c98e.png)

```
https://netty.io/news/2021/03/04/http3-0-0-1-Final.html
```

**Comment by normanmaurer** [comment]
Sorry but I think I need more infos.

**Comment by heixiaoma** [comment]
I use the latest version to test. It can pass. I can turn this off. Thank you
