### ISSUE TITLE
Is the HTTP3 server intentionally sending 4294967295 as the value for SETTINGS_MAX_FIELD_SECTION_SIZE in its SETTINGS frame?

### ISSUE THREAD

**Issue by jaikiran** [netty/netty-incubator-codec-http3#209]
Consider a HTTP3 server created as in the example https://github.com/netty/netty-incubator-codec-http3/blob/main/src/test/java/io/netty/incubator/codec/http3/example/Http3ServerExample.java. 

Such a server generates a `SETTINGS` frame for its peer client whenever the client connects to the server. There are a few parameters that are sent by the server to the client in those settings. One of them is the `SETTINGS_MAX_FIELD_SECTION_SIZE` whose value as noted in the RFC 9114[1] by default is unlimited.

When using the server as shown in the example, I see that the server sends a settings frame with this parameter's value set to `4294967295`, which is very "precise" value and thus raised my curiosity. Looking at the code here https://github.com/netty/netty-incubator-codec-http3/blob/main/src/main/java/io/netty/incubator/codec/http3/Http3CodecUtils.java#L35 it looks like this value is defaulted to `0xffffffffL` (which translates to `4294967295`). Was that default value really meant to be `4294967295`? If it was intentional then that's fine. But the choice of this value made me curious whether this was more a oversight and whether this default value here was meant to be `-1` (to represent "no specific value") and in such cases don't send this `SETTINGS_MAX_FIELD_SECTION_SIZE` in the SETTINGS frame (which doesn't allow negative values for the parameters).

[1] https://www.rfc-editor.org/rfc/rfc9114.html#SETTINGS_MAX_FIELD_SECTION_SIZE

**Comment by normanmaurer** [comment]
I really have a hard time to remember why I did choose this one :D Feel free to send a pr

**Comment by jaikiran** [comment]
Thank you Norman for the change and sorry I lost track of this one couldn't get to creating a PR.
