### ISSUE TITLE
QPack: Incorrect mapping of relative indices to absolute indices in field line representations

### ISSUE THREAD

**Issue by AlekseiEfimov** [netty/netty-incubator-codec-http3#249]
Relative dynamic table entry indices in field line representations are mapped to absolute indices values according to the following statement from RFC 9204 [Section 3.2.5 "Relative Indexing"](https://www.rfc-editor.org/rfc/rfc9204.html#name-relative-indexing): 

>  In a field line representation, a relative index of 0 refers to the entry with absolute index equal to Base - 1.

The usages of `QpackDecoderDynamicTable::getEntryRelativeEncodedField` in `QpackDecoder` need to be fixed to use the correct index mapping, eg calculate absolute index with `base - idx - 1` instead of `base - idx`.

Same issue needs to be fixed on the `QpackEncoder` side, when encoding indexed field lines, and literal field lines with name reference.

**Comment by normanmaurer** [comment]
@AlekseiEfimov want to do a PR ? Good catch!

**Comment by normanmaurer** [comment]
@AlekseiEfimov ping

**Comment by AlekseiEfimov** [comment]
@normanmaurer
Sorry for not getting back to you sooner. Regarding the PR: I'm not planning to work on it - just wanted to report the issue.

**Comment by normanmaurer** [comment]
@AlekseiEfimov can you have a look at https://github.com/netty/netty-incubator-codec-http3/pull/250 ? I think this should fix it.

**Comment by AlekseiEfimov** [comment]
The fix looks right to me.
