### ISSUE TITLE
SniHandler for HTTP/3

### ISSUE THREAD

**Issue by abezhovets** [netty/netty-incubator-codec-http3#45]
Is it possible to implement sni and how?

**Comment by normanmaurer** [comment]
not at the moment...

**Comment by abezhovets** [comment]
@normanmaurer 
There is a commit for SNI support
https://github.com/netty/netty-incubator-codec-quic/pull/313
but i need to pass `sniHostname` to custom handler. For http1/2, there is a `SniCompletionEvent` in `AbstractSniHandler`, for example. How can I pass `hostname`?

Can I help via pull request? Is it possible to do this via an event or can I give access to the fields? For example,
>((QuicheQuicSslSessionContext) ch.parent().sslEngine().getSession().getSessionContext()).context

and link the information I need through the attribute of sslContext.
