### ISSUE TITLE
QPACK to support dynamic table

### ISSUE THREAD

**Issue by kachayev** [netty/netty-incubator-codec-http3#6]
#3 implementation covers static table only.

**Comment by govi20** [comment]
@normanmaurer Interested in working on this. 

Though, I don't know much about HTTP3, QPACK. But willing to explore.

**Comment by yawkat** [comment]
if nobody else is working on this yet, im going to start on it

**Comment by normanmaurer** [comment]
As far as I know @NiteshKant is

**Comment by yawkat** [comment]
@NiteshKant can you confirm?

**Comment by NiteshKant** [comment]
@yawkat yes I am working on it, targeting next week to send a PR.

**Comment by yawkat** [comment]
thanks for the info!

**Comment by NiteshKant** [comment]
@yawkat draft PR for dynamic table: #131

**Comment by NiteshKant** [comment]
This was done sometime back (https://github.com/netty/netty-incubator-codec-http3/pull/131)
