### ISSUE TITLE
Interoperability with netty-codec-http2 and netty-codec-http

### ISSUE THREAD

**Issue by timboudreau** [netty/netty-incubator-codec-http3#78]
I'm looking at updating some code that uses codec-http to possibly use codec-http2's types instead, and going through the pro's and con's of translating requests into codec-http's types (existing code does not change) versus updating everything to want, for example, an `Http2Headers` and let HTTP 1.x requests by handled using HTTP2 idioms...

...and I run across this project, which looks like it started from a copy/paste of codec-http2, and think...am I going to be facing this again for HTTP3?

So, in general, this issue is a request to pay attention to interoperability and doing http3 support in a way that code that depends on codec-http2 can transparently use codec-http3 without modifications until it bumps up against something that is truly different in http3.  That looks a little more doable between http2 and http3 (common interface for Headers, etc.) than the much older codec-http.  Those of us who have built frameworks that are a layer on top of Netty will be profoundly grateful.

**Comment by normanmaurer** [comment]
@timboudreau i am not sure how doable this really is. That said i planned to have a handler to translate to h1 messages (just as we also have for h2). Most people really only care about h1 semantics on top of h2 / h3 imho

**Comment by normanmaurer** [comment]
This is related to https://github.com/netty/netty-incubator-codec-http3/pull/92

**Comment by normanmaurer** [comment]
I think this can be closed now with #92 in.
